

all: clean buildgen build


# %.tex: %.raw
# 	./raw2tex $< > $@
#
# %.tex: %.dat
# 	./dat2tex $< > $@



watch:
    #!/usr/bin/env bash
    while true; do
        inotifywait -e modify -r .
        just
    done

build: buildgen
	# latexmk -pdf -pdflatex="pdflatex" -use-make main.tex 
	tectonic -Z shell-escape main.tex
	# xelatex ./main.tex -shell-escape && biber main &&  xelatex -shell-escape ./main.tex && xelatex -shell-escape ./main.tex

# build-all: buildgen
#     #!/usr/bin/env xonsh
#     ind = 0
#     for i in [
#         "\\documentclass[aspectratio=169]{beamer}",
#         "\\documentclass[aspectratio=169,notes=only]{beamer}",
#         "\\documentclass[aspectratio=169,notes]{beamer}"
#     ]:
#         echo @(i) >> build/gen/Autoload.sty
#         just build
#         if ind == 0:
#             cp main.pdf output/slides.pdf
#         if ind == 1:
#             cp main.pdf output/notes.pdf
#         if ind == 2:
#             cp main.pdf output/notes_and_slides.pdf
#         ind += 1
#         sed -i '$d' build/gen/Autoload.sty # Remove last line

buildgen:
	# Create sections file
	echo > build/gen/sections.tex
	echo '%% THIS FILE IS AUTOMATICALLY GENERATED AT COMPILETIME %%' >> build/gen/sections.tex
	echo '%% DO NOT EDIT THIS FILE. IT SHOULD BE SAVE TO DELETE. %%' >> build/gen/sections.tex
	echo '\newcommand*{\ListOfAppendixWithoutExt}{%' 				 >> build/gen/sections.tex
	ls appendix/*.tex | sed 's|appendix/||' | sed 's/\.tex//' | sort --numeric-sort| sed 's|^|appendix/|' | sed 's/$/,/' >> build/gen/sections.tex
	echo '}%' 										 				 >> build/gen/sections.tex
	echo '\newcommand*{\ListOfSectionsWithoutExt}{%' 				 >> build/gen/sections.tex
	ls sections/*.tex | sed 's|sections/||' | sed 's/\.tex//' | sort --numeric-sort| sed 's|^|sections/|' | sed 's/$/,/' >> build/gen/sections.tex
	echo '}%' 														 >> build/gen/sections.tex
	# Create Autoload file
	#
	echo > build/gen/Autoload.sty
	echo '\ProvidesPackage{build/gen/Autoload}[0000/00/00 0.0.0 generated at compiletime]' >> build/gen/Autoload.sty
	echo '\input{build/gen/sections.tex}' >> build/gen/Autoload.sty
	echo '\endinput' >> build/gen/Autoload.sty


clean:
	rm build/gen/*
	touch build/gen/--files-in-this-directory-are-cleared-at-compiletime--

view:
    #!/usr/bin/env bash
    if [ -f /tmp/zathura_typst_presentation_pid ]; then
        cat /tmp/zathura_typst_presentation_pid | xargs kill 2> /dev/null
    fi
    zathura ./main.pdf &> /dev/null &
    echo $! > /tmp/zathura_typst_presentation_pid
    disown

add-entry:
    ./add_entry.sh
